---
name: awspub
summary: A tool to aid in the publication of aws images
description: |
  A tool to aid in the publication of AWS EC2 images.

  Note: this snap is provided and maintained by Canonical!
  (**not** by Amazon/AWS)
version: git
base: core22
confinement: strict
license: Apache-2.0
issues: https://github.com/canonical/awspub/issues

plugs:
  dot-aws:
    interface: personal-files
    read:
    - $HOME/.aws

apps:
  awspub:
    command: bin/awspub
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages
      # need to set $HOME to the real HOME here because this is a strict snap
      # and the creds for aws are in $HOME/.aws
      HOME: $SNAP_REAL_HOME
    plugs:
      - home
      - network
      - dot-aws

parts:
  awspub:
    plugin: python
    source: .
    stage-packages:
      - python3-poetry
    override-build: |
      craftctl default
      pip install .
      sed -i 's|'"$SNAPCRAFT_PART_INSTALL"'||' $SNAPCRAFT_PART_INSTALL/bin/awspub
